version: '2'
services:
  vulnerable_node:
    restart: always
    build: .
    ports:
      - "3000:3000"
#    links:
#      - postgres_db:postgres_db
    depends_on:
      - postgres_db

  postgres_db:
    restart: always
    environment:
      # To avoid the following error:
      #
      #   Error: Database is uninitialized and superuser password is not
      #   specified.  You must specify POSTGRES_PASSWORD for the superuser. Use
      #   "-e POSTGRES_PASSWORD=password" to set it in "docker run".
      #
      #   You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all
      #   connections without a password. This is *not* recommended. See
      #   PostgreSQL documentation about "trust"
      POSTGRES_HOST_AUTH_METHOD: trust    build: ./services/postgresql
    ports:
      - "5432:5432"
